version: "3.7"
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
  webserver:
    image: puckel/docker-airflow
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__LOAD__EXAMPLE=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgres://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./dataset:/usr/local/airflow/dataset
    ports:
      - "8080:8080"
    command: webserver
